# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'impact_table.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgImpacts(object):
    def setupUi(self, dlgImpacts):
        dlgImpacts.setObjectName("dlgImpacts")
        dlgImpacts.resize(618, 466)
        self.tableImpacts = QtWidgets.QTableWidget(dlgImpacts)
        self.tableImpacts.setGeometry(QtCore.QRect(15, 11, 591, 441))
        self.tableImpacts.setAlternatingRowColors(True)
        self.tableImpacts.setObjectName("tableImpacts")
        self.tableImpacts.setColumnCount(3)
        self.tableImpacts.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableImpacts.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableImpacts.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableImpacts.setHorizontalHeaderItem(2, item)

        self.retranslateUi(dlgImpacts)
        QtCore.QMetaObject.connectSlotsByName(dlgImpacts)

    def retranslateUi(self, dlgImpacts):
        _translate = QtCore.QCoreApplication.translate
        dlgImpacts.setWindowTitle(_translate("dlgImpacts", "Impacts Table"))
        item = self.tableImpacts.horizontalHeaderItem(0)
        item.setText(_translate("dlgImpacts", "Project"))
        item = self.tableImpacts.horizontalHeaderItem(1)
        item.setText(_translate("dlgImpacts", "Type"))
        item = self.tableImpacts.horizontalHeaderItem(2)
        item.setText(_translate("dlgImpacts", "Distance"))
